[package]
name = "untitled"
version = "0.1.0"
authors = ["ezra <ezra40b@gmail.com>"]
edition = "2018"

[dependencies]
diesel = { version = "1.4.4", features = ["postgres"] }
dotenv = "0.15.0"
sodiumoxide = "0.2.6"
rand = "0.8.3"